name: Build Windows EXE on Release

on:
  release:
    # Runs when you click "Publish release" in the UI (includes pre-releases).
    # Draft creation/edits won't trigger this.
    types: [published]

permissions:
  contents: write  # required to upload assets with the built-in GITHUB_TOKEN

concurrency:
  group: windows-build-${{ github.event.release.tag_name }}
  cancel-in-progress: true

jobs:
  build-windows:
    # Uncomment the next line if you want to SKIP pre-releases:
    # if: ${{ !github.event.release.prerelease }}
    runs-on: windows-latest

    steps:
      - name: Check out code at the release tag
        uses: actions/checkout@v4

      - name: Verify icon exists
        shell: pwsh
        run: |
          if (-not (Test-Path 'img/app.ico')) {
            Write-Error "Icon not found at img/app.ico. Commit the ICO or update the path."
            exit 1
          }

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          pip install pillow mss pyinstaller

      - name: Build EXE with PyInstaller
        shell: pwsh
        run: |
          pyinstaller --name SciVizTool --onefile --windowed --noconfirm --clean -i img/app.ico sci_viz_tool.py
          if (!(Test-Path "dist/SciVizTool.exe")) {
            Write-Error "Build failed: dist/SciVizTool.exe not found."
            exit 1
          }
          dir dist

      - name: Upload EXE to this Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/SciVizTool.exe
          tag_name: ${{ github.event.release.tag_name }}
          fail_on_unmatched_files: true
          generate_release_notes: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
